"""add homepage config table

Revision ID: homepage_config_001
Revises: enhance_audit_log_schema
Create Date: 2025-01-06 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'homepage_config_001'
down_revision = 'fix_audit_metadata_column'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_title', sa.String(length=255), nullable=True),
    sa.Column('hero_subtitle', sa.String(length=500), nullable=True),
    sa.Column('hero_cta_text', sa.String(length=100), nullable=True),
    sa.Column('hero_image_url', sa.String(length=500), nullable=True),
    sa.Column('featured_product_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('categories_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('homepage_config')
    # ### end Alembic commands ###
