name: web-ci

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: web/package.json

      - name: Install dependencies
        run: npm ci

      - name: Generate OpenAPI types
        run: npm run types:api

      - name: Build
        run: npm run build

